/*
 * Product aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Subscription struct {

	Heading string `json:"heading,omitempty"`
	// short description
	Description string `json:"description,omitempty"`
	// VAS-P subscription identifier
	ServiceId string `json:"serviceId,omitempty"`
	// cost of subscription
	Cost float32 `json:"cost,omitempty"`
	// recurrent payment
	Pay string `json:"pay,omitempty"`
}
